Now it builds
This line was causing errors, resulting in a build failing

The error:

/usr/bin/ld: runtime.o:(.bss+0x120): multiple definition of `RAM'; cbmbasic.o:(.bss+0x20): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:7: cbmbasic] Error 1